name: CI for Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://github.com/processing/processing4/releases/download/processing-1294-4.3.1/processing-4.3.1-linux-x64.tgz
        tar -xvzf processing-4.3.1-linux-x64.tgz
        sudo mv processing-4.3.1 /usr/local/processing
        sudo ln -s /usr/local/processing/processing-java /usr/local/bin/processing-java

    - name: Verify installation
      run: processing-java --help

    - name: Run Processing sketch
      run: |
        processing-java --sketch=`pwd` --run
    
    - name: Build Processing sketch
      run: |
        processing-java --sketch=`pwd` --build
